name: CI/CD

on:
  push:
    branches:
      - "**"
  release:
    types: [released, prereleased]

jobs:
  Build-Test-Release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Set tag name
        run: if ${{ github.event_name == 'release' }}; then
          tag=${{ github.ref_name }};
          elif ${{ github.event_name == 'workflow_dispatch' }}; then
          tag=${{ inputs.tag }};
          fi;
          echo "TAG=$tag" >> $GITHUB_ENV;

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install app dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Commit to page branch
        if: ${{ github.head_ref == 'main' }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Add changes"

      - name: Push changes
        if: ${{ github.head_ref == 'main' }}
        uses: ad-m/github-push-action@master
        with:
          branch: page
